### ISSUE TITLE
Removing quote from an object property with string key

### ISSUE THREAD

**Issue by Akumzy** [Tom-Bonnike/vscode-formatting-toggle#31]
Thank you for developing this very nice plugin 
Please can your make it not to remove an object property with a string key
like that $route thanks
```
<script>
export default {
  name: "app",
  methods: {
  aMethod(to, from){
}

},
  watch: {
   "$route": "aMethod"
  }
};
</script>
```

**Comment by Tom-Bonnike** [comment]
Hi Akumzy. Sorry, I missed this issue, but you should open it in Prettier https://github.com/prettier/prettier. This plugin only allows you to toggle Prettier on/off.
