### ISSUE TITLE
Doesn't overwrite workspace settings

### ISSUE THREAD

**Issue by peterp** [Tom-Bonnike/vscode-formatting-toggle#36]
This extension doesn't work as intended when you've got workspace settings.

**Comment by Tom-Bonnike** [comment]
Thanks @peterp. I’ll check that as soon as I have time.

**Comment by Tom-Bonnike** [comment]
@peterp can you describe the exact issue you’re facing? I don’t think I’ll be able to override workspace settings:
- They are stored in a file that is shared accross the team, so you don’t want to be changing those…
- They are *always* prioritized over user settings.

From my understanding there’s three possible cases:
1) Your workspace settings enable the formatter ➡️ you can use your formatter accross the whole project and it shouldn’t be a problem.
2) Your workspace settings disable the formatter ➡️you shouldn’t be using your formatter so you have no reason to want to enable it.
3) Your workspace settings don’t include any formatting settings :arrow_right: your user settings (which this extension modifies) will be used instead.

**Comment by peterp** [comment]
Hey @Tom-Bonnike,

We have some files that are formatted and some files that aren't yet...  so I want to be able to toggle the formatter for those file.

You explanation makes sense, I didn't realise that it was modifying the configuration files.

**Comment by Tom-Bonnike** [comment]
Ah, yeah… I don’t think that’s something this extension should be handling. I think you could use `.prettierignore` files: https://prettier.io/docs/en/ignore.html for that? The Prettier extension respects those settings :)

**Comment by peterp** [comment]
Thanks!
