### ISSUE TITLE
Not working with "Javascript React" files

### ISSUE THREAD

**Issue by pashute** [Tom-Bonnike/vscode-formatting-toggle#37]
Regardless of toggle (via clicking on the "formatting" in the bottom right corner), it formats. 

I'm using "React native tools" which include Beautify. 

This is happening in a .js code file listed as  "JavaScript React". 

Not sure what information you require to determine the problem. 

vscode: 1.25.1  
user settings: 
"editor.formatOnSave": false,
    "files.autoSave": "afterDelay",
   "files.associations": {
        "*.js": "javascriptreact"
    },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "emmet.triggerExpansionOnTab": true,
    "prettier.singleQuote": true,
    "javascript.validate.enable": false,

**Comment by Tom-Bonnike** [comment]
Hey,

- I see `editor.formatOnSave: false`, if you open your settings file, do you confirm that you can see it getting toggled to `true` and `false` on every click?
- Do you maybe have workspace settings that impact formatting?

This extension should work fine with Beautify.

**Comment by pashute** [comment]
workspace:
  "files.autoSave": "afterDelay",
  "editor.formatOnSave": true,  // i got this unintentionally from a programmer sharing my project...
removed it now (it was set while Formatting X) 

confirm that format on save toggles in user-settings from true to false correctly. 

That solved the problem!!
