### ISSUE TITLE
How this extension work?

### ISSUE THREAD

**Issue by shirshak55** [Tom-Bonnike/vscode-formatting-toggle#38]
First thanks for such a great plugin.

Do it uses prettier or what? How do I identify it bro? Currently I was having problem with laravel blade so It will be easy for me :) Is there way I can customize the formatting .

**Comment by Tom-Bonnike** [comment]
For formatting options, please see the vscode-prettier extensions. https://github.com/prettier/prettier-vscode

**Comment by shirshak55** [comment]
Hi i only have basic prettier installed. So basic prettier work out of box for php? 

I thought it was for js only. 

I think it may be irrelevant question but is there anyway to configure prettier for php like 1 level indentation after each if statement  etc?

currently if content is 

```laravel-blade
@if(condition)
    <p>asdf</p>
@endif
```
when i format it shows 
```laravel-blade
@if(condition)
<p>asdf</p>
@endif
```

I think the indentation looks better although i know prettier is optinated about its styling is there anything we can do it to change :)


Again thanks :)

**Comment by Tom-Bonnike** [comment]
Yeah there is an official PHP plugin for Prettier (https://github.com/prettier/plugin-php), which is probably what `vscode-prettier` uses? I don’t know.

This extension is only to be able to enable/disable the formatting. I’m sorry but I can’t really help!
