### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by coliff** [Tom-Bonnike/vscode-formatting-toggle#39]
would be nice to have an icon for this extension.

**Comment by coliff** [comment]
thanks for pushing the update live - looks great. All the extensions I have installed have icons now. :-)

**Comment by Tom-Bonnike** [comment]
![image](https://user-images.githubusercontent.com/9154236/54204736-23271f00-44d5-11e9-80bc-656ad4f291d5.png)

Thanks a lot :)
