### ISSUE TITLE
Toggle not working if editor.formatOnSave is set both on user and workspace settings

### ISSUE THREAD

**Issue by ghaschel** [Tom-Bonnike/vscode-formatting-toggle#40]
I have `editor.formatOnSave` set on user settings to be able to sync with my home preferences and also have it set on workspace settings to make some settings default for our company workspace.

Apparently it only takes the user settings in consideration, because once I disable `editor.formatOnSave` manually on my workspace settings it works as it should.

It happens using prettier on `ts` and beautify in `html` files

**Comment by Tom-Bonnike** [comment]
Hey. Please take a look at https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/36.
