### ISSUE TITLE
Ability to toggle when using language scoped settings

### ISSUE THREAD

**Issue by RiFi2k** [Tom-Bonnike/vscode-formatting-toggle#41]
Maybe I'm missing a way this can work out the box but if not it would be great if you could support the toggling of format on save when you are using it scoped to each language. Doesn't seem to be able to toggle it currently.

```json
"editor.formatOnSave": false,
"[php]": {
  "editor.formatOnSave": true
},
"[javascript]": {
  "editor.formatOnSave": true
}
```
I had to work around a similar situation so just to possibly save you a couple minutes of looking it up, this is how I went about checking for it. Using the always handy lodash has and get methods.

```javascript
const config = vscode.workspace.getConfiguration();
if (has(config, '[php]')) {
  const phpScopedObj = get(config, '[php]');
  if (phpScopedObj['editor.formatOnSave']) {
    // Things to do when it exists.
  }
}
```
You would really make my day if you could somehow work out a way to toggle these as well, I haven't found anything yet to cover this situation and it gets old editing the settings file everytime so I don't polute the git logs of older sites without explicit formating settings in them with a bunch of formatting changes from my user settings.

**Comment by Tom-Bonnike** [comment]
Mhmmm I get how it’d be useful but maybe this should be solved at the formatter’s level, e.g. by ignoring extensions/files in specific projects (using `.prettierignore`)?

Maybe VSCode workspace settings could help? The extension doesn’t override those.

**Comment by RiFi2k** [comment]
These are actually workspace settings, I'll give you a current usecase it would be helpful for me.

Refactoring a large app made a few years ago, I need to edit one variable in a JS file with 3k lines of code, already have ported in the new formatting settings but not ready to format that whole file with the new es6 prettier/eslint settings (maybe it over-rides a function() with an arrow function somewhere that uses a this inside or swaps out string concats etc), so I have to go into settings turn it off for JS make my edit then turn it back on for editing the smaller files I do want to format. Tons of use cases for lang scoping the formatting settings and possibly not wanting one out of 10 saves to format, at least I run in to it 3 to 4 times every couple weeks.

**Comment by Tom-Bonnike** [comment]
Meh, I still think `.prettierignore` is the way to go here but alright. Is it enough for your use-case if the extension toggles those language-specific options? Or would you really want to be able to quickly toggle on & off a specific extension?

**Comment by RiFi2k** [comment]
So I mean, I get it. I can prettier/eslint ignore a file or even probably a blob of files/types. But I think the great part about your extension is not needing to mess with your configuration files at all for the one off scenarios. Realistically if this gets added, I use it in this manner maybe once a month moving forward... but to me that once a month convience is the point of having the extension, if it doesn't help me solve a problem it won't stay installed for very long. Now that being said, on your end you have to say ok I've had the thing for x number of years / downloads and nobody has asked for this before is it worth it. Trust me I see it both ways.

What I was thinking were I you, was to get an array of 5-6 most popular languages throw them in an array. Then hook into the already existing toggle all off / toggle all on and pop those 5-6 possibilities (if they exist), off or on with the click. No need for configuration options or and jazz just maybe add in two loops of checking if those scoped configs exist and whichever ones do off or on them. Maybe adds a few miliseconds to execution but I'm assuming you have the settings object already so your checking if 5-6 values exist in an object at the end of the day if nobody uses it, and you can add another feature to your extension.

Either way you rock for spending your time dev-ing a free open source extension and if it doesn't happen I'll still keep your extension because it adds value and convience to VSCode which I probably use more than any other program I have.

**Comment by Tom-Bonnike** [comment]
I got that.

Would it satisfy you if the extension toggled everything, including the `[extension]` configs? Or do you want to be able to toggle **a single extension** only?

**Comment by RiFi2k** [comment]
All at the same time gets me what I'm personally looking for.

**Comment by Tom-Bonnike** [comment]
I was about to implement it buuuut why wouldn’t you just ditch the `editor.*` settings in your language specific configurations? You‘d then rely exclusively on the extension to enable/disable the formatting globally, which is kind of its goal.
I’m asking because if I toggle all language specific settings, they will always be synced to the same values, which makes them useless.

I could instead only toggle the formatting settings for the currently opened file’s extension, but I’m not really sure it’s worth adding so much complexity to the extension and could also make things more confusing for users.

**Comment by RiFi2k** [comment]
Sounds good man, no worries.

My personal setup / usecase is not indicative to most of the world anyways. I'm always in and out of pretty large sized projects that all have project specific VSCode settings in the repos. Just on the one project alone there are PHP, Vue, JS, JSON, YAML, HTML, CSS, SCSS files I'll be in and out of but some are not in a state/position to be fully formatted some use the full ESlint config, some are older JS files. So for me, I'll just stick too turning off the workspace format settings every once in awhile till it annoys me enough and I hack together a solution.

I appreciate the candor and you thinking about implementing it for me, I know it's a bit nutty for just one usecase.

**Comment by RiFi2k** [comment]
Actually your idea is pretty valid, now that I think about it, to pull just the formatting completely out and use your extension. If everyone agrees that may just be a winner. Thanks!
