### ISSUE TITLE
doesn't work with multiple vscode windows 

### ISSUE THREAD

**Issue by Ashtonian** [Tom-Bonnike/vscode-formatting-toggle#46]
With multiple vscode windows open if you toggle it in one it effects the other. This will also result in a inconsistent state where one window will show "formatting:x" indicating disabled when in fact its enabled and vice versa.

**Comment by Tom-Bonnike** [comment]
Thanks for the report, I’ll take a look soon, never considered this. :)

**Comment by Tom-Bonnike** [comment]
The fix should go live with the next release, thanks again for the report :)
