### ISSUE TITLE
formattingToggle.deactivateFor

### ISSUE THREAD

**Issue by Jonas1312** [Tom-Bonnike/vscode-formatting-toggle#47]
Thanks for your extension 🙂

That would be nice to have an option `formattingToggle.deactivateFor`, in my case I would like to disable `formatOnSave` but keep `formatOnPaste` and `formatOnType` when I'm contributing to existing code.

Thanks

**Comment by Tom-Bonnike** [comment]
Hey. Unless I’m misunderstanding, this is already possible with:
```json
"formattingToggle.activateFor": ["formatOnPaste", "formatOnType"]
```

**Comment by Jonas1312** [comment]
Sorry it wasn't clear.

When I click the "formatting" button your extension disable all three options (`formatOnPaste`, `formatOnType`, `formatOnSave`). I would like to keep `formatOnType` and `formatOnPaste` enabled.

If I'm not mistaken "formattingToggle.activateFor" works only when you enable formatting, but it's not possible to control which of the three settings your extension disable

**Comment by Tom-Bonnike** [comment]
Would this work for you?
```json
{
  "editor.formatOnSave": false,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "formattingToggle.activateFor": ["formatOnPaste", "formatOnType"]
}
```

I think that should work.

**Comment by Jonas1312** [comment]
Nope that's not really what I'm looking for

I would like two configurations, that is, two states:
- State 1: everything on, I use this configuration when I'm working alone on a project, so that all my codes are properly formatted with the same formatter.
```
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
```
- State 2: everything on except format all document (`formatOnSave`), which is convenient when contributing to existing code which wasn't properly formatted, and you don't want a minor change to modify the whole file.
```
  "editor.formatOnSave": false,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
```

I tried your suggestion:
```
{
  "editor.formatOnSave": false,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "formattingToggle.activateFor": ["formatOnPaste", "formatOnType"]
}
```

and the two states it produced are:
- State 1: toggle formatting off => everything off
```
  "editor.formatOnSave": false,
  "editor.formatOnPaste": false,
  "editor.formatOnType": false,
```
- State 2: toggle formatting on => everything on except format all document (`formatOnSave`)
```
  "editor.formatOnSave": false,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
```

**Comment by Tom-Bonnike** [comment]
Oh. I understand now, although I have to admit I dont really see what the actual use-case is.
The point of this extension is to quickly enable/disable *all* formatting. Not allow you to toggle on/off specific settings 😅 

You might want to look into other extensions such as https://marketplace.visualstudio.com/items?itemName=rebornix.toggle.
I’ll close this, happy to reconsider if more people want something like this, but again I’m not sure it gives much value.

**Comment by Tom-Bonnike** [comment]
I want to tackle this, moved to #48
