### ISSUE TITLE
Please add "deactivateFor"

### ISSUE THREAD

**Issue by slavdok** [Tom-Bonnike/vscode-formatting-toggle#48]
_Originally posted by @Tom-Bonnike in https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/47#issuecomment-510000701_
> I’ll close this, happy to reconsider if more people want something like this

As the [other poster requested](https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/47), please add "deactiveFor" to allow us to configure the behaviour to our liking.

As for the value, here is my scenario:
1) I've configured editor's `formatOnPaste` and `formatOnType` to be always `true`.
2) I want "formattingToggle" button to **only** affect `formatOnSave` (toggle on and off)

Why 1)?
Cause for the code **_I_** edit (i.e. paste and type), I want it nice and organized.

Why 2)?
Cause not everyone uses VScode. In a big company, on a big project, there are tons of people writing code, and not always following formatting guides (whether I should re-format everyone else's file is outside the scope of this discussion). So, majority is existing code is not formatted to the same standards

If, every time I modify a single line for a fix and save, it will reformat the _whole_ file, it will make huge changes on commits, resulting in potential conflicts on many lines when merged back to other branches (with other non-formatting people working on same files). So no, I don't want "formatOnSave" to be on when working on collaborative work (but I still want my changes formatted, so I have editor setup to always format on paste and type)

But when working on my own files, I want to toggle "formatOnSave" to true.

Yes, I could achieve this through different `.vscode` per-workspace files... Or through that other extension that binds keyboard shortcuts to different settings....
**But** the whole point of the **quick** status bar toggle is to avoid setting up custom workspace settings per each folder I work on, and to avoid remembering keyboard shortcuts.

We are not asking to change default behaviour. We are asking to give us the _option_ to configure our custom behaviour.

Thank you.

**Comment by Tom-Bonnike** [comment]
Sorry for not answering earlier. You kinda convinced me. I’ll look into adding that option soon.

**Comment by Tom-Bonnike** [comment]
I started working on this but I realise now that the proper solution to your problem is maybe not to add another setting… The extension could probably just have a `formattingToggle.affects: […]` setting, if you don’t put `formatOnType` and `formatOnPaste` in there, it would not impact the values that are already set in your settings, so it would only toggle `formatOnSave` as you want it.

And then it would also work for `activateFor`, if you don’t put `formatOnType` in there and it’s `false`, then it would stay `false`.

What do you think?

**Comment by slavdok** [comment]
Sounds reasonable to me

**Comment by Tom-Bonnike** [comment]
The `formattingToggle.affects` setting will go live with V2 in a few minutes.
