### ISSUE TITLE
Does not work with ESLint extension

### ISSUE THREAD

**Issue by vlanemcev** [Tom-Bonnike/vscode-formatting-toggle#53]
To ESLint - https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint 
you need to specify the property:

"editor.codeActionsOnSave": {
      "source.fixAll": true
}

instead of formatOnSave

**Comment by Tom-Bonnike** [comment]
This extension is meant to toggle formatters (like Prettier), not linters.
It never was supposed to impact ESLint since most people only want it to run on projects where they have a config file. Are you using a global config? 😕 

This should work:
```
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
```

**Comment by Tom-Bonnike** [comment]
I’ll close for now.
