### ISSUE TITLE
Does not work in Remote - Containers or GitHub Codespaces

### ISSUE THREAD

**Issue by felipecrs** [Tom-Bonnike/vscode-formatting-toggle#56]
When I hit the button, nothing happens.

![LImUe9rHMB](https://user-images.githubusercontent.com/29582865/93720246-300edf00-fb5e-11ea-8a4c-b33f8d41c2d0.gif)

VSCode 1.49.1

**Comment by Tom-Bonnike** [comment]
Works for me, v1.49.1. If you open the debug console (CMD+Shift+P, `View: Debug Console`), is there anything in any of the tabs?

**Comment by felipecrs** [comment]
The settings are not being changed. I was not able to find any logs for this extension as well.

![6LyWZWEVYB](https://user-images.githubusercontent.com/29582865/93770716-689bd080-fbd1-11ea-85fb-5b6287170d6f.gif)

**Comment by felipecrs** [comment]
Ok, just found where the issue is: on `devcontainer`s, both using Remote - Containers extension and GitHub Codespaces.

**Comment by Tom-Bonnike** [comment]
Mhmm, seems like I have some reading to do: https://code.visualstudio.com/api/advanced-topics/remote-extensions
Can’t promise I’ll fix this quick, but I’ll investigate what I need to do to support remote development. :)

**Comment by felipecrs** [comment]
![AE8sBvKXwD](https://user-images.githubusercontent.com/29582865/93772928-48214580-fbd4-11ea-84fa-d9eedf228c2e.gif)

If there is anything else I can do to help you figure out the Issue, please tell.

> Can’t promise I’ll fix this quick.

Sure! I totally understand.

Thank you for this great extension anyway, very handy. :)

**Comment by felipecrs** [comment]
By the way, the extension works fine on WSL and SSH (the two other flavors of Remote Development).

**Comment by Tom-Bonnike** [comment]
Good to know, thanks Felipe!

**Comment by Tom-Bonnike** [comment]
Caused by https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/58
