### ISSUE TITLE
bisect results

### ISSUE THREAD

**Issue by platproit** [Tom-Bonnike/vscode-formatting-toggle#60]
Issue Type: <b>Bug</b>

extension bisect identified as a problem extension

Extension version: 2.0.0
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.06GB free)|
|Process Argv|\\\\wsl$\\Debian\\home\\dev1\\.profile --crash-reporter-id deb06a08-2e95-455c-be88-6e5d4c5b1a89|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by Tom-Bonnike** [comment]
Hi. I have no idea what any of this means. Could you tell me a little more? :)

**Comment by platproit** [comment]
vs code extension were acting up and i performed a bisect to localize the extension causing an error and this report popped up in the results. i have no idea either but thought you could use the data.,

**Comment by Tom-Bonnike** [comment]
Without any stack trace I can’t do much but thanks anyway 🤷‍♂️
