### ISSUE TITLE
Formatting Toggle does not work?

### ISSUE THREAD

**Issue by mityaua** [Tom-Bonnike/vscode-formatting-toggle#63]
A few weeks ago, your extension stopped working on all my machines. All I see in the panel is an icon. There are no other errors in the terminal. When i click on the icon, nothing happens. Complete uninstallation VSC and reinstallation did not help.

What could be the problem?

Windows 10 (x64) 1803
VSC 1.62.3
Formatting Toggle (v3.0.0)

![Screenshot_1](https://user-images.githubusercontent.com/20481332/142872389-83ecf99c-1f09-4fce-8644-ff5b69e3376c.png)

**Comment by Tom-Bonnike** [comment]
- Do you have Workspace settings affecting the formatting options?
- Did you set a `formattingToggle.affects` option? [It now expects a full path for formatting settings](https://github.com/Tom-Bonnike/vscode-formatting-toggle/blob/master/CHANGELOG.md).

**Comment by mityaua** [comment]
Setting the full path helped me., thanks. Sorry if I missed the сhange Log.

**Comment by pm0u** [comment]
Thanks for noting workspace settings - my organization had `formatOnSave` set in the workspace and this makes it impossible to toggle.
