### ISSUE TITLE
Add Setting for Status Bar Text

### ISSUE THREAD

**Issue by dgrebb** [Tom-Bonnike/vscode-formatting-toggle#67]
It would be excellent if one could define the text accompanying `$(check)` and `$(x)` in the Status Bar.

I'm also curious if anyone would be interested in customizing the icons, as well. Personally, I quite like `$(check)` and `$(x)`.

**Comment by Tom-Bonnike** [comment]
Hey Dan. I just released this in 3.2.0, I ended up renaming the setting to `statusBarText` instead of `statusBarLabel` just for consistency throughout the code 👀

Thank you so much for your work, you’re a star 🌟
