### ISSUE TITLE
Incorrect Formatting Issue

### ISSUE THREAD

**Issue by 4samsamAC** [Tom-Bonnike/vscode-formatting-toggle#70]
I am facing an issue with the "Formatting Toggle" extension in Visual Studio Code. The extension is adding unwanted spaces in my code when formatting is enabled, causing errors in my script.
<a href="https://imgur.com/CEKCdU6"><img src="https://i.imgur.com/CEKCdU6.gif" title="source: imgur.com" /></a>

**Comment by Tom-Bonnike** [comment]
Hi, this can’t be related to the extension as it’s only handling whether the formatting is enabled or not. It must be related to some badly configured ESLint rule or a Prettier bug.
