### ISSUE TITLE
Issues with Version: 1.85.0 and/or workspace settings

### ISSUE THREAD

**Issue by tordans** [Tom-Bonnike/vscode-formatting-toggle#72]
Version: 1.85.0
Formatting Toggle v3.2.0

I was using the Status Bar Toggle Button to disable autoformatting on file save. However, that stopped working.
Could this be due to changes in a recent VS Code Update?
One thing I noticed is, that I have the setting on workspace level, not on user level. However the toggle is active but does not toggle…
<img width="932" alt="image" src="https://github.com/Tom-Bonnike/vscode-formatting-toggle/assets/111561/9dbd0439-4458-461a-ba5d-b8ddcf67746d">
<img width="931" alt="image" src="https://github.com/Tom-Bonnike/vscode-formatting-toggle/assets/111561/9323dad0-c637-44cd-9cc5-cd971fbc4677">
<img width="156" alt="image" src="https://github.com/Tom-Bonnike/vscode-formatting-toggle/assets/111561/85df27a0-cadc-402e-bc4b-873b92874215">

**Comment by marksieczkowski** [comment]
I having the same behavior

**Comment by Tom-Bonnike** [comment]
https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/61

https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/58

**Comment by Tom-Bonnike** [comment]
The extension purposefully doesn’t override workspace settings, see the README. More discussions in https://github.com/Tom-Bonnike/vscode-formatting-toggle/issues/61

Sorry for the delayed answer. Let me know if I’m incorrectly understanding this issue.
